---
- name: Configure MongoDB
  hosts: all
  become: true

  roles:
    - db

#  tasks:
#  - name: Add an apt key
#    apt_key:
#      keyserver: keyserver.ubuntu.com
#      id: EA312927

#  - name: Add Mongo repository
#    apt_repository:
#      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
#      state: present

#  - name: Update repositories cache and install Mongo package
#    apt:
#      name: mongodb-org
#      state: present
#      update_cache: yes

#  - name: Enable service mongod
#    service:
#      name: mongod
#      enabled: yes
